### ISSUE TITLE
Conflicted function type in pre-defined function

### ISSUE THREAD

**Issue by c8ef** [ustb-owl/MimiC#2]
When I try to compile some simple program, like (https://github.com/pku-minic/compiler-dev-test-cases/blob/master/testcases/lv9/16_sort2.c), the compiler always gives the following error:

`demo.c:4:14: error: id: putint, conflicted function type`

the putint definition is defined in `src/main.cpp`, but I don't know why it is a conflicted function type.

**Comment by c8ef** [comment]
Use the autotest tool will get the same result:
```bash
running test "sysyruntimelibrary/functional/00_main.sy" ... sysyruntimelibrary/functional/00_main.sy:4:14: error: id: putint, conflicted function type
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL
running test "sysyruntimelibrary/functional/01_var_defn2.sy" ... sysyruntimelibrary/functional/01_var_defn2.sy:4:14: error: id: putint, conflicted function type
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL
running test "sysyruntimelibrary/functional/02_var_defn3.sy" ... sysyruntimelibrary/functional/02_var_defn3.sy:4:14: error: id: putint, conflicted function type
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL
running test "sysyruntimelibrary/functional/03_arr_defn2.sy" ... sysyruntimelibrary/functional/03_arr_defn2.sy:4:14: error: id: putint, conflicted function type
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL
running test "sysyruntimelibrary/functional/04_arr_defn3.sy" ... sysyruntimelibrary/functional/04_arr_defn3.sy:4:14: error: id: putint, conflicted function type
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL
running test "sysyruntimelibrary/functional/05_arr_defn4.sy" ... sysyruntimelibrary/functional/05_arr_defn4.sy:4:14: error: id: putint, conflicted function type
/usr/bin/ld: /lib/x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x17): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL
```

**Comment by MaxXSoft** [comment]
Hello!

I tried compiling the current version of the repository with Apple Clang 12.0.5 on macOS 12.6.3, and Clang 15.0.7 on Debian 11, and ran:

```
./mmcc 16_sort2.c -S -o out.S
```

No error were generated.

I'm not sure what C++ compiler and OS you are using, please provide more detailed information.

**Comment by c8ef** [comment]
It is really weird......At first, I use `./mmcc demo.c`, now I use  `./mmcc demo.c -S -o out.S`, all get the same error......
My develop environment:
```
$ uname -a
Linux 6.1.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.7-1 (2023-01-18) x86_64 GNU/Linux
$ gcc --version
gcc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ clang --version
Debian clang version 16.0.0 (++20230124121624+5265adc73721-1~exp1~20230124121637.543)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
And I find the way that can work on my machine. If I comment [these lines](https://github.com/ustb-owl/MimiC/blob/master/src/main.cpp#L141-L143) and write function declaration manually, the compiler works fine.......I don't know the difference between the two ways.
BTW, when building the project, `-Werror` option triggers some error message:
```
[11/60] Building CXX object CMakeFiles/mmcc.dir/src/driver/compiler.cpp.o
FAILED: CMakeFiles/mmcc.dir/src/driver/compiler.cpp.o
/usr/bin/c++ -DAPP_NAME="\"MimiC Compiler\"" -DAPP_VERSION=\"0.0.1\" -DAPP_VERSION_MAJOR=0 -DAPP_VERSION_MINOR=0 -DAPP_VERSION_PATCH=1 -I/home/miao/MimiC/src -I/home/miao/MimiC/3rdparty/xstl -Wall -Werror -std=c++17 -MD -MT CMakeFiles/mmcc.dir/src/driver/compiler.cpp.o -MF CMakeFiles/mmcc.dir/src/driver/compiler.cpp.o.d -o CMakeFiles/mmcc.dir/src/driver/compiler.cpp.o -c /home/miao/MimiC/src/driver/compiler.cpp
In file included from /home/miao/MimiC/src/driver/compiler.cpp:1:
/home/miao/MimiC/src/driver/compiler.h: In constructor ‘mimic::driver::Compiler::Compiler()’:
/home/miao/MimiC/src/driver/compiler.h:23:31: error: member ‘mimic::driver::Compiler::eval_’ is used uninitialized [-Werror=uninitialized]
   23 |       : parser_(lexer_), ana_(eval_),
      |                               ^~~~~
cc1plus: all warnings being treated as errors
[18/60] Building CXX object CMakeFiles/mmcc.dir/src/main.cpp.o
FAILED: CMakeFiles/mmcc.dir/src/main.cpp.o
/usr/bin/c++ -DAPP_NAME="\"MimiC Compiler\"" -DAPP_VERSION=\"0.0.1\" -DAPP_VERSION_MAJOR=0 -DAPP_VERSION_MINOR=0 -DAPP_VERSION_PATCH=1 -I/home/miao/MimiC/src -I/home/miao/MimiC/3rdparty/xstl -Wall -Werror -std=c++17 -MD -MT CMakeFiles/mmcc.dir/src/main.cpp.o -MF CMakeFiles/mmcc.dir/src/main.cpp.o.d -o CMakeFiles/mmcc.dir/src/main.cpp.o -c /home/miao/MimiC/src/main.cpp
In file included from /home/miao/MimiC/src/main.cpp:10:
/home/miao/MimiC/src/driver/compiler.h: In constructor ‘mimic::driver::Compiler::Compiler()’:
/home/miao/MimiC/src/driver/compiler.h:23:31: error: member ‘mimic::driver::Compiler::eval_’ is used uninitialized [-Werror=uninitialized]
   23 |       : parser_(lexer_), ana_(eval_),
      |                               ^~~~~
cc1plus: all warnings being treated as errors
```
And thanks for your quick response!

**Comment by MaxXSoft** [comment]
Thanks for reporting these issues! I have successfully reproduced them on Debian 12 with GCC 12.2.0, and have fixed them.

The first issue is that GCC complains about the initialization order of members of the `Compiler` class, because `Analyzer` is initialized before `Evaluator`, but it requires a reference to the `Evaluator` class first. This issue can be fixed by changing declaration order of the two members, see commit 6eeacc185e56ac944515c08861a2a0e6ecc05d73.

The second issue, which leads to a `conflicted function type` error, is caused by dangling references. The `Analyzer` class uses a hash map with the key type `std::string_view` to store all function definitions:

https://github.com/ustb-owl/MimiC/blob/88c2c541c807f21710e9c55859b3b8bb248e1f2d/src/mid/analyzer.h#L91

The map actually stores `ast.id()`, i.e. a `std::string` reference, as a key:

https://github.com/ustb-owl/MimiC/blob/88c2c541c807f21710e9c55859b3b8bb248e1f2d/src/mid/analyzer.cpp#L216-L219

But the `ast` is freed after the current loop, so the reference becomes a dangling reference:

https://github.com/ustb-owl/MimiC/blob/88c2c541c807f21710e9c55859b3b8bb248e1f2d/src/driver/compiler.cpp#L28-L35

In the next loop, `std::string_view` in the hash map references a garbage memory, something magical happens in the program, and then an error occurrs (sadly it doesn't crash).

To prevent this issue, we can use `std::string` instead of `std::string_view`, see commit aeb9c049ab0ed22c9a5063931cea5f45375f3118.

**Comment by c8ef** [comment]
Now it works! Thanks again for your prompt bug fix and detailed explanation!!
